let firstValue = 3;
let secondValue = 7;
let thirdValue = 5;
let result = (Number(firstValue)+Number(secondValue)+Number(thirdValue))/3;
console.log(result);
let fourthValue = 7;
let fifthValue = '7';
console.log(fourthValue==fifthValue);
console,log(fourthValue===fifthValue);
let price = 12999;
let priceDiscount = prompt('Price discount', '17');
console.log(priceDiscount);
let salePrice = Number(price)-(Number(price)/100 * Number(priceDiscount));
console.log(salePrice);